#ifndef _LA_BLAS_PRIVATE_H
#define _LA_BLAS_PRIVATE_H

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif

#include <libla/index.h>


extern double   F77_FUNC(ddot)   (const la_index *n,
                                  const double   *x,
                                  const la_index *incx,
                                  const double   *y,
                                  const la_index *incy);
extern double   F77_FUNC(dnrm2)  (const la_index *n,
                                  const double   *x,
                                  const la_index *incx);
extern double   F77_FUNC(dasum)  (const la_index *n,
                                  const double   *x,
                                  const la_index *incx);
extern la_index F77_FUNC(idamax) (const la_index *n,
                                  const double *x,
                                  const la_index *incx);
extern void     F77_FUNC(dswap)  (const la_index *n,
                                  double         *x,
                                  const la_index *incx,
                                  double         *y,
                                  const la_index *incy);
extern void     F77_FUNC(dcopy)  (const la_index *n,
                                  const double   *x,
                                  const la_index *incx,
                                  double         *y,
                                  const la_index *incy);
extern void     F77_FUNC(daxpy)  (const la_index *n,
                                  const double   *alpha,
                                  const double   *x,
                                  const la_index *incx,
                                  double         *y,
                                  const la_index *incy);
extern void     F77_FUNC(drotg)  (double         *a,
                                  double         *b,
                                  double         *c,
                                  double         *s);
extern void     F77_FUNC(drotmg) (double         *d1,
                                  double         *d2,
                                  double         *b1,
                                  const double   *b2,
                                  double         *p);
extern void     F77_FUNC(drot)   (const la_index *n,
                                  double         *x,
                                  const la_index *incx,
                                  double         *y,
                                  const la_index *incy,
                                  const double   *c,
                                  const double   *s);
extern void     F77_FUNC(drotm)  (const la_index *n,
                                  double         *x,
                                  const la_index *incx,
                                  double         *y,
                                  const la_index *incy,
                                  const double   *p);
extern void     F77_FUNC(dscal)  (const la_index *n,
                                  const double   *alpha,
                                  double         *x,
                                  const la_index *incx);
extern void     F77_FUNC(dgemv)  (const char     *trans,
                                  const la_index *m,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  const double   *x,
                                  const la_index *incx,
                                  const double   *beta,
                                  double         *y,
                                  const la_index *incy);
extern void     F77_FUNC(dgbmv)  (const char     *trans,
                                  const la_index *m,
                                  const la_index *n,
                                  const la_index *kl,
                                  const la_index *ku,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  const double   *x,
                                  const la_index *incx,
                                  const double   *beta,
                                  double         *y,
                                  const la_index *incy);
extern void     F77_FUNC(dsbmv)  (const char     *uplo,
                                  const la_index *n,
                                  const la_index *k,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  const double   *x,
                                  const la_index *incx,
                                  const double   *beta,
                                  double         *y,
                                  const la_index *incy);
extern void     F77_FUNC(dspmv)  (const char     *uplo,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *ap,
                                  const double   *x,
                                  const la_index *incx,
                                  const double   *beta,
                                  double         *y,
                                  const la_index *incy);
extern void     F77_FUNC(dsymv)  (const char     *uplo,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  const double   *x,
                                  const la_index *incx,
                                  const double   *beta,
                                  double         *y,
                                  const la_index *incy);
extern void     F77_FUNC(dtbmv)  (const char     *uplo,
                                  const char     *trans,
                                  const char     *diag,
                                  const la_index *n,
                                  const la_index *k,
                                  const double   *a,
                                  const la_index *lda,
                                  double         *x,
                                  const la_index *incx);
extern void     F77_FUNC(dtpmv)  (const char     *uplo,
                                  const char     *trans,
                                  const char     *diag,
                                  const la_index *n,
                                  const double   *ap,
                                  double         *x,
                                  const la_index *incx);
extern void     F77_FUNC(dtrmv)  (const char     *uplo,
                                  const char     *trans,
                                  const char     *diag,
                                  const la_index *n,
                                  const double   *a,
                                  const la_index *lda,
                                  double         *x,
                                  const la_index *incx);
extern void     F77_FUNC(dtbsv)  (const char     *uplo,
                                  const char     *trans,
                                  const char     *diag,
                                  const la_index *n,
                                  const la_index *k,
                                  const double   *a,
                                  const la_index *lda,
                                  double         *x,
                                  const la_index *incx);
extern void     F77_FUNC(dtpsv)  (const char     *uplo,
                                  const char     *trans,
                                  const char     *diag,
                                  const la_index *n,
                                  const double   *ap,
                                  double         *x,
                                  const la_index *incx);
extern void     F77_FUNC(dtrsv)  (const char     *uplo,
                                  const char     *trans,
                                  const char     *diag,
                                  const la_index *n,
                                  const double   *a,
                                  const la_index *lda,
                                  double         *x,
                                  const la_index *incx);
extern void     F77_FUNC(dger)   (const la_index *m,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *x,
                                  const la_index *incx,
                                  const double   *y,
                                  const la_index *incy,
                                  double         *a,
                                  const la_index *lda);
extern void     F77_FUNC(dsyr)   (const char     *uplo,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *x,
                                  const la_index *incx,
                                  double         *a,
                                  const la_index *lda);
extern void     F77_FUNC(dspr)   (const char     *uplo,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *x,
                                  const la_index *incx,
                                  double         *ap);
extern void     F77_FUNC(dsyr2)  (const char     *uplo,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *x,
                                  const la_index *incx,
                                  const double   *y,
                                  const la_index *incy,
                                  double         *a,
                                  const la_index *lda);
extern void     F77_FUNC(dspr2)  (const char     *uplo,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *x,
                                  const la_index *incx,
                                  const double   *y,
                                  const la_index *incy,
                                  double         *ap);
extern void     F77_FUNC(dgemm)  (const char     *transa,
                                  const char     *transb,
                                  const la_index *m,
                                  const la_index *n,
                                  const la_index *k,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  const double   *b,
                                  const la_index *ldb,
                                  const double   *beta,
                                  double         *c,
                                  const la_index *ldc);
extern void     F77_FUNC(dtrsm)  (const char     *side,
                                  const char     *uplo,
                                  const char     *transa,
                                  const char     *diag,
                                  const la_index *m,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  double         *b,
                                  const la_index *ldb);
extern void     F77_FUNC(dtrmm)  (const char     *side,
                                  const char     *uplo,
                                  const char     *transa,
                                  const char     *diag,
                                  const la_index *m,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  double         *b,
                                  const la_index *ldb);
extern void     F77_FUNC(dsymm)  (const char     *side,
                                  const char     *uplo,
                                  const la_index *m,
                                  const la_index *n,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  const double   *b,
                                  const la_index *ldb,
                                  const double   *beta,
                                  double         *c,
                                  const la_index *ldc);
extern void     F77_FUNC(dsyrk)  (const char     *uplo,
                                  const char     *trans,
                                  const la_index *n,
                                  const la_index *k,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  const double   *beta,
                                  double         *c,
                                  const la_index *ldc);
extern void     F77_FUNC(dsyr2k) (const char     *uplo,
                                  const char     *trans,
                                  const la_index *n,
                                  const la_index *k,
                                  const double   *alpha,
                                  const double   *a,
                                  const la_index *lda,
                                  const double   *b,
                                  const la_index *ldb,
                                  const double   *beta,
                                  double         *c,
                                  const la_index *ldc);

#endif /*_LA_BLAS_PRIVATE_H */
