# actors methods
actors       <- function(object, ...) UseMethod("actors")
group        <- function(object, ...) UseMethod("group")
ngroup       <- function(object, ...) UseMethod("ngroup")
group.traits <- function(object, ...) UseMethod("group.traits")

# iproc.frame methods
iproc.frame  <- function(object, ...) UseMethod("iproc.frame")

# matrix multiplicaiton
mul          <- function(x, y, ...) UseMethod("mul")
tmul         <- function(x, y, ...) UseMethod("tmul")

advance      <- function(object, ...) UseMethod("advance")
cursor       <- function(object, ...) UseMethod("cursor")
finished     <- function(object, ...) UseMethod("finished")
from         <- function(object, ...) UseMethod("from")
grad         <- function(object, ...) UseMethod("grad")
has.loops    <- function(object, ...) UseMethod("has.loops")
insert       <- function(object, ...) UseMethod("insert")
loglik       <- function(object, ...) UseMethod("loglik")
log.probs    <- function(object, ...) UseMethod("log.probs")
messages     <- function(object, ...) UseMethod("messages")
max.from     <- function(object, ...) UseMethod("max.from")
max.nto      <- function(object, ...) UseMethod("max.nto")
max.to       <- function(object, ...) UseMethod("max.to")
model        <- function(object, ...) UseMethod("model")
nreceiver    <- function(object, ...) UseMethod("nreceiver")
nsender      <- function(object, ...) UseMethod("nsender")
nties        <- function(object, ...) UseMethod("nties")
nto          <- function(object, ...) UseMethod("nto")
probs        <- function(object, ...) UseMethod("probs")
receivers    <- function(object, ...) UseMethod("receivers")
reset        <- function(object, ...) UseMethod("reset")
senders      <- function(object, ...) UseMethod("senders")
size         <- function(object, ...) UseMethod("size")
started      <- function(object, ...) UseMethod("started")
to           <- function(object, ...) UseMethod("to")
vars         <- function(object, ...) UseMethod("vars")
value        <- function(object, ...) UseMethod("value")
